### ISSUE TITLE
mallinfo.c:14:22: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#120] opened 2020-09-18 14:19 UTC
Trying to build on travis CI, Debian docker container.

```
cc -g -O2 -fdebug-prefix-map=/home/travis/build/Whonix/hardened_malloc=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -fstack-clash-protection -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -Werror -march=native -Wmissing-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I include -DCONFIG_SEAL_METADATA=false -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false -DSLAB_CANARY=true -DCONFIG_EXTENDED_SIZE_CLASSES=true -Wl,-z,relro -Wl,-z,now -Wl,--as-needed,-z,defs,-z,relro,-z,now,-z,nodlopen,-z,text  mallinfo.c  -lpthread -o mallinfo

mallinfo.c: In function 'main':

mallinfo.c:14:22: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("arena: %zu\n", info.arena);

                    ~~^     ~~~~~~~~~~

                    %u

mallinfo.c:15:24: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("ordblks: %zu\n", info.ordblks);

                      ~~^     ~~~~~~~~~~~~

                      %u

mallinfo.c:16:23: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("smblks: %zu\n", info.smblks);

                     ~~^     ~~~~~~~~~~~

                     %u

mallinfo.c:17:22: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("hblks: %zu\n", info.hblks);

                    ~~^     ~~~~~~~~~~

                    %u

mallinfo.c:18:23: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("hblkhd: %zu\n", info.hblkhd);

                     ~~^     ~~~~~~~~~~~

                     %u

mallinfo.c:19:24: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("usmblks: %zu\n", info.usmblks);

                      ~~^     ~~~~~~~~~~~~

                      %u

mallinfo.c:20:24: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("fsmblks: %zu\n", info.fsmblks);

                      ~~^     ~~~~~~~~~~~~

                      %u

mallinfo.c:21:25: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("uordblks: %zu\n", info.uordblks);

                       ~~^     ~~~~~~~~~~~~~

                       %u

mallinfo.c:22:25: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("fordblks: %zu\n", info.fordblks);

                       ~~^     ~~~~~~~~~~~~~

                       %u

mallinfo.c:23:25: error: format '%zu' expects argument of type 'size_t', but argument 2 has type 'int' [-Werror=format=]

     printf("keepcost: %zu\n", info.keepcost);

                       ~~^     ~~~~~~~~~~~~~

                       %u

mallinfo.c:8:5: error: ignoring return value of 'malloc', declared with attribute warn_unused_result [-Werror=unused-result]

     malloc(1024 * 1024 * 1024);

     ^~~~~~~~~~~~~~~~~~~~~~~~~~

mallinfo.c:9:5: error: ignoring return value of 'malloc', declared with attribute warn_unused_result [-Werror=unused-result]

     malloc(16);

     ^~~~~~~~~~

mallinfo.c:10:5: error: ignoring return value of 'malloc', declared with attribute warn_unused_result [-Werror=unused-result]

     malloc(32);

     ^~~~~~~~~~

mallinfo.c:11:5: error: ignoring return value of 'malloc', declared with attribute warn_unused_result [-Werror=unused-result]

     malloc(64);

     ^~~~~~~~~~

cc1: all warnings being treated as errors
```

full log:
https://travis-ci.com/github/Whonix/hardened_malloc/builds/185210851

**Comment by thestinger** [comment] 2020-09-18 15:26
This is caused by building the tests with `-Werror`. The tests deliberately do things like leaking memory in order to test the implementation. I can't reproduce this because `-Werror` isn't passed when I run `make test`.

**Comment by thestinger** [comment] 2020-09-18 15:34
Also, glibc has a broken implementation of mallinfo which is why it's hard-wired as disabled for the glibc ABI. I still want to be able to test it regardless, even though it's disabled. Using `%zu` is the correct format specifier for the mallinfo fields. In dlmalloc, where it originates, the modern ABI uses `size_t`. I can't explain why glibc implemented it incorrectly. The way they do it has undefined signed overflows inside their malloc implementation when simply using malloc regularly. It wraps around with signed overflow since they're using `int` (32-bit, signed integer) to track sizes on all architectures. Even for a 32-bit on 64-bit, it may be possible to overflow it.

I could disable this test when building with glibc. It's nice to test that the API just doesn't do anything though, in my opinion. I could go out of the way to work around the warning but I'd rather not, and I don't know why the tests would be using `-Werror` in your build since I don't think that's what I've done in the Makefile.

**Comment by thestinger** [comment] 2020-09-18 15:44
https://github.com/GrapheneOS/hardened_malloc/commit/8906c0941a8c0a3c7bcb1ae3348c7baa93565871 expands the test to testing it before and after running free, which ends up avoiding this, but in general, you're not going to be able to build the tests with `-Werror`, so you need to fix that. My change isn't fixing a problem, just testing more than before. It's perfectly fine to write a test that purposely leaks memory. I won't avoid doing things like that. The whole simple-memory-corruption directory is full of tests that deliberately corrupt memory. If compilers weren't so clueless, they would detect many of the errors at compile-time, since they're all simple, obvious cases. It would be nice to have more complex / thorough testing but it is what it is right now. Better than nothing. The tests currently barely cover what the hardening features provide. It's difficult to test all of it. Tests outside of `simple-memory-corruption` aren't actually part of a real test suite right now either. They're just used to manually test some things. I also have a lot of tests that are not committed to the repository. It's the type of thing that needs someone interested to do a lot of work on it.

**Comment by thestinger** [comment] 2020-11-10 19:15
I modified the test to work around the glibc bug documented in `man mallinfo` in the BUGS section. The `mallinfo` implementation already simply zeroes all of the fields when using hardened_malloc with glibc. I don't think much else can be done about this, since they never had any interest in fixing the API. It would require an ABI change for newer code with a way of preserving backwards compatibility. It does result in undefined signed overflows in glibc, but they've never cared about that kind of thing.

**Closed by thestinger** 2020-11-10 19:15 UTC

**Comment by suyogc143** [comment] 2023-01-10 14:37
![Uploading IMG_20230110_195248.jpg…]()

**Comment by thestinger** [comment] 2023-01-10 16:54
@suyogc143 Unsure what you're trying to post but it didn't work.
